language: node_js

build_image: shippable/minv2

node_js:
  - "0.10"
 # - "0.11"
  #- "0.8"

env:
 - Foo=bar
 #- Bar=foo
 
matrix:
  allow_failures:
    - node_js: "0.11"
  exclude:
    - node_js: "0.8"
  include:
    - node_js: "0.10"
      env: test=aaa
      
script: "npm run-script test-travis"

after_script:
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- --ui=bdd --reporter=xunit-file
  - ./node_modules/.bin/istanbul report cobertura --dir shippable/codecoverage/
  - cp README.md ./shippable
  
notifications:
  email:
    recipients:
      - test_ci2@yahoo.in 
      - testnotifications.beta@yahoo.in
    on_success: never
    on_failure: always
  irc: 
    #pull_requests: true
    #channels:
      - "chat.freenode.net#test-irc"

#archive: true
